export const enum ErrorType {
    REGISTRATION = "REGISTRATION ERROR",
    USER = "USER ERROR",
    CONVERSATION = "CONVERSATION ERROR",
    MESSAGE = "MESSAGE ERROR",
    SETTINGS = "SETTINGS ERROR",
}
